### ISSUE TITLE
add drum loops and progressions

### ISSUE THREAD

**Issue by RustoMCSpit** [Fannon/midi-chord-pack#2]
https://archive.org/details/themagicofmidiv1

**Comment by RustoMCSpit** [comment]
https://github.com/ldrolez/free-midi-chords

**Comment by RustoMCSpit** [comment]
https://splice.com/blog/how-to-make-drum-patterns/
https://splice.com/blog/wp-content/uploads/2019/10/MIDI-Drum-Patterns.zip

**Comment by RustoMCSpit** [comment]
https://mobilemusicpro.com/collections/free-downloads

**Comment by RustoMCSpit** [comment]
https://github.com/ldrolez/free-midi-chords/issues/3

**Comment by RustoMCSpit** [comment]
apologies for the spam just wanted to see if anyone knew how to collect this and make a github for it cause i dont really understand this stuff, have a great day everyone and apologies for the inconvenience!!

**Comment by Fannon** [comment]
No problem - that's a nice list :)

But I don't have an intention to add other peoples MIDI here as this project here only comes with MIDI that I'll generate myself and therefore is completely free for me to publish.

**Comment by RustoMCSpit** [comment]
> No problem - that's a nice list :)
> 
> But I don't have an intention to add other peoples MIDI here as this project here only comes with MIDI that I'll generate myself and therefore is completely free for me to publish.

i mean, these are all free lists too and you cant copyright grooves or progressioba
